### ISSUE TITLE
plain text emoji file

### ISSUE THREAD

**Issue by jeetelongname** [hpcodecraft/ASCIImoji#13]
Hey so this is not an issue per say but I always wanted a plain text file for shell scripts and other use cases. Here is that file. 

I used this function to generate it
```js
function makeText() {
  for ([key, values] of Object.entries(dictionary)) {
    if (typeof values.ascii === 'function') {
      continue // we need to skip functions as this is a static list
    }
    console.log(`${[key, ...values.words]} ${values.ascii}`)
  }
}
```
I then capture that output in the shell into a file. its not a very elegant way to generate this file but it works for the most part. 
I also have to ignore the emojis that take in a function as this is a static file but for me anyway its a small price to pay. If you want me to spin this into a PR where it generates a plain text file whenever it changes then I would be happy to oblige

[ascii-emoji.txt](https://github.com/hpcodecraft/ASCIImoji/files/7071553/ascii-emoji.txt)

**Comment by hpcodecraft** [comment]
Hey @jeetelongname,

I finally added it! 😂 https://github.com/hpcodecraft/ASCIImoji/blob/master/dist/text-file/asciimoji.txt

Thank you for your function, I was able to use it. I did one minor change though: When the key and one of the words is the same, it's not repeated anymore.

Here is the build script: https://github.com/hpcodecraft/ASCIImoji/blob/master/src/text-file/build.js

**Comment by jeetelongname** [comment]
awesome thanks!
