### ISSUE TITLE
asciimoji isn't defined

### ISSUE THREAD

**Issue by techmandan** [hpcodecraft/ASCIImoji#8]
When I tried to include your JS (tried both from DIST and SRC) I always got an error in console:
`Uncaught ReferenceError: asciimoji is not defined`
It's the last **_asciimoji_**
`(jQuery,window,document,asciimoji);`
When I tried to remove it, consoles start looping other undefined, because I'm new to JQuery, I don't know how to fix that.
Thanks for helping me out!

**Comment by hpcodecraft** [comment]
You'll have to include both scripts to your page, asciimoji.js and asciimoji.jquery.js (or their minified versions). The jQuery plugin only wraps the actual function but doesn't include it.

I hope that helps!

**Comment by techmandan** [comment]
Thanks, it works. It wasn't in readme and I'm little new to jquery and js..
